### ISSUE TITLE
Create Seamless Authentication Flows: Sign-in, Sign-up/Register

### ISSUE THREAD

**Issue by deepak4566** [CloudVizz/CloudVizz#1]
**Current Behavior:**
Currently, our platform offers only traditional email/password-based authentication for user sign-in and registration. Users are required to manually create an account by providing their email and password details. This limited authentication method may pose usability challenges for users who prefer alternative sign-in options.

**Desired Behavior:**
We aim to enhance our platform's authentication system by implementing OAuth-based sign-in and sign-up options with Google and GitHub integration. In addition to the existing email/password registration process, users will have the flexibility to sign in or sign up using their Google or GitHub accounts. Upon visiting the sign-in or sign-up page, users will be presented with the choice to authenticate via Google, GitHub, or the traditional email/password method. By selecting the "Sign in with Google" or "Sign in with GitHub" options, users will be redirected to the respective authentication provider's page to authorize access. After authorization, users will be redirected back to our platform, where they will be authenticated and granted access. This enhancement aims to streamline the authentication process, providing users with convenient sign-in and sign-up options while maintaining security and usability standards.

**Comment by Kanishk3813** [comment]
assign me this issue.

**Comment by deepak4566** [comment]
> assign me this issue.

@Kanishk3813  Sure , Here we go
