### ISSUE TITLE
Change folder structure in Cloudvizz

### ISSUE THREAD

**Issue by deepak4566** [CloudVizz/CloudVizz#6]
## Current Situation 
Currently , we don't correct folder structure to place things .

## Desired Situation 
come up with correct folder structure to place things appropriately .

**Comment by deepak4566** [comment]
@sujallimje can u take up this ???

**Comment by sujallimje** [comment]
Assign me this issue

**Comment by deepak4566** [comment]
Here you go

**Comment by sujallimje** [comment]
can someone look into this for pull request
 "Warning: The config file was not found at .github/labeler.yml. Make sure it exists and that this action has the correct access rights."

**Comment by deepak4566** [comment]
> can someone look into this for pull request "Warning: The config file was not found at .github/labeler.yml. Make sure it exists and that this action has the correct access rights."

yup , im reviewing it

**Comment by sujallimje** [comment]
i think its solved now
you can merge and check.
